In [23]:
import requests
from bs4 import BeautifulSoup
from itertools import izip
import pandas as pd

In [24]:
url = "http://www.nuforc.org/webreports/ndxloc.html"

In [25]:
content = requests.get(url)

In [26]:
soup = BeautifulSoup(content.text, "html.parser")

In [27]:
soup.prettify()

u'<html>\n <head>\n  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">\n   <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">\n   <html>\n    <head>\n     <meta content="text/html; charset=utf-8" http-equiv="Content-Type">\n      <meta content="Mozilla/4.5b2 [en] (WinNT; I) [Netscape]" name="GENERATOR">\n       <title>\n        ndxLocOut\n       </title>\n      </meta>\n     </meta>\n    </head>\n    <body>\n     <font face="Arial,Helvetica">\n      <font size="+1">\n       National UFO Reporting\rCenter\n      </font>\n     </font>\n     <br>\n      <font face="Arial,Helvetica">\n       <font size="+1">\n        Report Index by State / Province\n       </font>\n      </font>\n      <br>\n       <i>\n        Click on links for details\n       </i>\n       <p>\n        <a href="http://www.nwlink.com/~ufocntr">\n         NUFORC Home\n        </a>\n        <br>\n        </br>\n       </p>\n      </br>\n     </br>\n    </body>\n   </html>\n  </meta>\n </head>\n <body>\n  <table cellspacing="1">\n   <thead>\n    <tr>\n     <th bgcolor="#c0c0c0" bordercolor="#000000">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       Reports\n      </font>\n     </th>\n     <th bgcolor="#c0c0c0" bordercolor="#000000">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       Count\n      </font>\n     </th>\n    </tr>\n   </thead>\n   <tbody>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxl.html">\n        UNSPECIFIED/INTERNATIONAL\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       8362\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlAB.html">\n        ALBERTA,CANADA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       485\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlAK.html">\n        ALASKA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       522\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlAL.html">\n        ALABAMA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1010\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlAR.html">\n        ARKANSAS\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       871\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlAZ.html">\n        ARIZONA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       3803\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlBC.html">\n        BRITISH COLUMBIA,CAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1001\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlCA.html">\n        CALIFORNIA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       12793\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlCO.html">\n        COLORADO\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       2272\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlCT.html">\n        CONNECTICUT\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1350\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlDC.html">\n        DISTRICT OF COLUMBIA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       132\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlDE.html">\n        DELAWARE\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       298\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlFL.html">\n        FLORIDA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       6061\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlGA.html">\n        GEORGIA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1978\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlHI.html">\n        HAWAII\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       500\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlIA.html">\n        IOWA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       942\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlID.html">\n        IDAHO\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       879\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlIL.html">\n        ILLINOIS\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       3428\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlIN.html">\n        INDIANA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1860\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlKS.html">\n        KANSAS\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       897\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlKY.html">\n        KENTUCKY\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1242\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlLA.html">\n        LOUISIANA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       882\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMA.html">\n        MASSACHUSETTS\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1950\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMB.html">\n        MANITOBA,CANADA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       208\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMD.html">\n        MARYLAND\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1369\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlME.html">\n        MAINE\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       886\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMI.html">\n        MICHIGAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       2837\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMN.html">\n        MINNESOTA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1560\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMO.html">\n        MISSOURI\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       2154\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMS.html">\n        MISSISSIPPI\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       592\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlMT.html">\n        MONTANA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       748\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNB.html">\n        NEW BRUNSWICK,CAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       161\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNC.html">\n        NORTH CAROLINA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       2731\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlND.html">\n        NORTH DAKOTA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       192\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNE.html">\n        NEBRASKA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       529\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNF.html">\n        NEWFOUNDLAND,CAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       36\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNH.html">\n        NEW HAMPSHIRE\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       829\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNJ.html">\n        NEW JERSEY\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       2113\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNM.html">\n        NEW MEXICO\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1204\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNS.html">\n        NOVA SCOTIA,CAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       192\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNT.html">\n        NORTHWEST TERRITORY\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       24\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNV.html">\n        NEVADA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1282\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlNY.html">\n        NEW YORK\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       4442\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlOH.html">\n        OHIO\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       3333\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlOK.html">\n        OKLAHOMA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1075\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlON.html">\n        ONTARIO,CAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       2022\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlOR.html">\n        OREGON\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       2641\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlPA.html">\n        PENNSYLVANIA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       3650\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlPE.html">\n        PRINCE EDW ISLAND\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       24\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlPQ.html">\n        PROV OF QUE,CAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       102\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlPR.html">\n        PUERTO RICO\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       37\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlQC.html">\n        QC\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       243\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlRI.html">\n        RHODE ISLAND\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       448\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlSA.html">\n        SASKATCHEWAN,CAN\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       39\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       <a href="ndxlSC.html">\n        SOUTH CAROLINA\n       </a>\n      </font>\n     </td>\n     <td align="RIGHT">\n      <font color="#000000" face="Calibri" style="FONT-SIZE:11pt">\n       1664\n      </font>\n     </td>\n    </tr>\n    <tr valign="TOP">\n     <td>\n      <font color="#000000"

In [28]:
#soup.find_all("a.href")
states=[]
for link in soup.find_all('a'):  # this will find all the hyper links
    # print type(link)  ## <class 'bs4.element.Tag'>
    #print link
    states.append(str(link.get_text()))
    


states = states[1:]

print states

['UNSPECIFIED/INTERNATIONAL', 'ALBERTA,CANADA', 'ALASKA', 'ALABAMA', 'ARKANSAS', 'ARIZONA', 'BRITISH COLUMBIA,CAN', 'CALIFORNIA', 'COLORADO', 'CONNECTICUT', 'DISTRICT OF COLUMBIA', 'DELAWARE', 'FLORIDA', 'GEORGIA', 'HAWAII', 'IOWA', 'IDAHO', 'ILLINOIS', 'INDIANA', 'KANSAS', 'KENTUCKY', 'LOUISIANA', 'MASSACHUSETTS', 'MANITOBA,CANADA', 'MARYLAND', 'MAINE', 'MICHIGAN', 'MINNESOTA', 'MISSOURI', 'MISSISSIPPI', 'MONTANA', 'NEW BRUNSWICK,CAN', 'NORTH CAROLINA', 'NORTH DAKOTA', 'NEBRASKA', 'NEWFOUNDLAND,CAN', 'NEW HAMPSHIRE', 'NEW JERSEY', 'NEW MEXICO', 'NOVA SCOTIA,CAN', 'NORTHWEST TERRITORY', 'NEVADA', 'NEW YORK', 'OHIO', 'OKLAHOMA', 'ONTARIO,CAN', 'OREGON', 'PENNSYLVANIA', 'PRINCE EDW ISLAND', 'PROV OF QUE,CAN', 'PUERTO RICO', 'QC', 'RHODE ISLAND', 'SASKATCHEWAN,CAN', 'SOUTH CAROLINA', 'SOUTH DAKOTA', 'SK', 'TENNESSEE', 'TEXAS', 'UTAH', 'VIRGINIA', 'VIRGIN ISLANDS', 'VERMONT', 'WASHINGTON', 'WISCONSIN', 'WEST VIRGINIA', 'WYOMING', 'YUKON', 'YT']

In [29]:
len(soup.find_all("font"))

144

In [30]:
type(soup.font)

bs4.element.Tag

In [31]:
print soup.findAll('font')[7].next
type(soup)

8362

bs4.BeautifulSoup

In [32]:
num_count=[]

for i in xrange(7,len(soup.find_all("font")), 2):
    num_count.append(str(soup.findAll('font')[i].next))

In [33]:
num_count = [int(x) for x in num_count]

In [34]:
state_count = [x for x in izip(states, num_count)]

#sighting_rank_state = sorted(state_count, reverse=True, key=lambda x: x[1]) ; sighting_rank_state

#for stkey in state_dict:
#    print stkey
#sighting = {x.lower():[num_count[i]] for i,x in enumerate(states)} ; sighting

In [35]:
sum( [info[1] for info in state_count] )

111724

In [36]:
df = pd.read_csv("US_State_population2016.csv")
df['population'][0].replace (",", "",1) 


state_dict = {st[1:].lower():df['StateCode'].values[i] for i, st in enumerate(df['State'].values)}
state_dict
df['Country'] = ['USA' for i in range(56)]  # Add a new column: 'USA'.

In [37]:
# Add some Canada columns (not all done yet)

df.loc[len(df)] = ['ON', 'ONTARIO,CAN', '13,448,494', 'CAN']

df.loc[len(df)] = ['AB', 'ALBERTA,CANADA', '4,067,175', 'CAN']

df.loc[len(df)] = ['BC', 'BRITISH COLUMBIA,CAN', '4,648,055', 'CAN']

df.loc[len(df)] = ['Manitoba', 'MANITOBA,CANADA', '1,278,365', 'CAN']

df.loc[len(df)] = ['NEW BRUNSWICK,CAN', 'NEW BRUNSWICK,CAN', '747,101', 'CAN']


df

            StateCode                      State  population Country
0                  AK                     Alaska     741,894     USA
1                  AL                    Alabama   4,863,300     USA
2                  AR                   Arkansas   2,988,248     USA
3                  AS             American Samoa      54,343     USA
4                  AZ                    Arizona   6,931,071     USA
5                  CA                 California  39,250,017     USA
6                  CO                   Colorado   5,540,545     USA
7                  CT                Connecticut   3,576,452     USA
8                  DC                         DC     681,170     USA
9                  DE                   Delaware     952,065     USA
10                 FL                    Florida  20,612,439     USA
11                 GA                    Georgia  10,310,371     USA
12                 GU                       Guam     161,785     USA
13                 HI                     Hawaii   1,428,557     USA
14                 IA                       Iowa   3,134,693     USA
15                 ID                      Idaho   1,683,140     USA
16                 IL                   Illinois  12,801,539     USA
17                 IN                    Indiana   6,633,053     USA
18                 KS                     Kansas   2,907,289     USA
19                 KY                   Kentucky   4,436,974     USA
20                 LA                  Louisiana   4,681,666     USA
21                 MA              Massachusetts   6,811,779     USA
22                 MD                   Maryland   6,016,447     USA
23                 ME                      Maine   1,331,479     USA
24                 MI                   Michigan   9,928,301     USA
25                 MN                  Minnesota   5,519,952     USA
26                 MO                   Missouri   6,093,000     USA
27                 MP   Northern Mariana Islands      52,344     USA
28                 MS                Mississippi   2,988,726     USA
29                 MT                    Montana   1,042,520     USA
..                ...                        ...         ...     ...
31                 ND               North Dakota     757,952     USA
32                 NE                   Nebraska   1,907,116     USA
33                 NH              New Hampshire   1,334,795     USA
34                 NJ                 New Jersey   8,944,469     USA
35                 NM                 New Mexico   2,081,015     USA
36                 NV                     Nevada   2,940,058     USA
37                 NY                   New York  19,745,289     USA
38                 OH                       Ohio  11,646,273     USA
39                 OK                   Oklahoma   3,923,561     USA
40                 OR                    Oregon    4,093,465     USA
41                 PA               Pennsylvania  12,784,227     USA
42                 PR                Puerto Rico   3,411,307     USA
43                 RI               Rhode Island   1,056,426     USA
44                 SC             South Carolina   4,961,119     USA
45                 SD               South Dakota     865,454     USA
46                 TN                  Tennessee   6,651,194     USA
47                 TX                      Texas  27,862,596     USA
48                 UT                       Utah   3,051,217     USA
49                 VA                   Virginia   8,411,808     USA
50                 VI        U.S. Virgin Islands     103,574     USA
51                 VT                    Vermont     624,594     USA
52                 WA                 Washington   7,288,000     USA
53                 WI                  Wisconsin   5,778,708     USA
54                 WV              West Virginia   1,831,102     USA
55                 WY                    Wyoming     585,501     USA
56                 ON                ONTARIO,CAN  13,448,494     CAN
57                 AB             ALBERTA,CANADA   4,067,175     CAN
58                 BC       BRITISH COLUMBIA,CAN   4,648,055     CAN
59           Manitoba            MANITOBA,CANADA   1,278,365     CAN
60  NEW BRUNSWICK,CAN          NEW BRUNSWICK,CAN     747,101     CAN

[61 rows x 4 columns]

In [38]:
df['nsightings'] = [0 for n in range(len(df))]

for sight_info in state_count:
    #if df [df['State'] == "CALIFORNIA"]:
    pass
    
    try:
        statecode = state_dict[sight_info[0].lower()]
        #print statecode
        index = df.loc[df['StateCode']==statecode].index[0]
        #print index
        df.loc[index, 'nsightings'] = sight_info[1]
    except:
        #statecode = state_dict[sight_info[0]]
        #print statecode
        pass

In [39]:
df

,StateCode,State,population,Country,nsightings
0,AK,Alaska,"741,894",USA,522
1,AL,Alabama,"4,863,300",USA,1010
2,AR,Arkansas,"2,988,248",USA,871
3,AS,American Samoa,"54,343",USA,0
4,AZ,Arizona,"6,931,071",USA,3803
5,CA,California,"39,250,017",USA,12793
6,CO,Colorado,"5,540,545",USA,2272
7,CT,Connecticut,"3,576,452",USA,1350
8,DC,DC,"681,170",USA,0
9,DE,Delaware,"952,065",USA,298
10,FL,Florida,"20,612,439",USA,6061
11,GA,Georgia,"10,310,371",USA,1978
12,GU,Guam,"161,785",USA,0
13,HI,Hawaii,"1,428,557",USA,500
14,IA,Iowa,"3,134,693",USA,942
15,ID,Idaho,"1,683,140",USA,879
16,IL,Illinois,"12,801,539",USA,3428
17,IN,Indiana,"6,633,053",USA,1860
18,KS,Kansas,"2,907,289",USA,897
19,KY,Kentucky,"4,436,974",USA,1242
20,LA,Louisiana,"4,681,666",USA,882
21,MA,Massachusetts,"6,811,779",USA,1950
22,MD,Maryland,"6,016,447",USA,1369
23,ME,Maine,"1,331,479",USA,886
24,MI,Michigan,"9,928,301",USA,2837
25,MN,Minnesota,"5,519,952",USA,1560
26,MO,Missouri,"6,093,000",USA,2154
27,MP,Northern Mariana Islands,"52,344",USA,0
28,MS,Mississippi,"2,988,726",USA,592
29,MT,Montana,"1,042,520",USA,748
...,...,...,...,...,...
31,ND,North Dakota,"757,952",USA,192
32,NE,Nebraska,"1,907,116",USA,529
33,NH,New Hampshire,"1,334,795",USA,829
34,NJ,New Jersey,"8,944,469",USA,2113
35,NM,New Mexico,"2,081,015",USA,1204
36,NV,Nevada,"2,940,058",USA,1282
37,NY,New York,"19,745,289",USA,4442
38,OH,Ohio,"11,646,273",USA,3333
39,OK,Oklahoma,"3,923,561",USA,1075
40,OR,Oregon,"4,093,465",USA,0
41,PA,Pennsylvania,"12,784,227",USA,3650
42,PR,Puerto Rico,"3,411,307",USA,37
43,RI,Rhode Island,"1,056,426",USA,448
44,SC,South Carolina,"4,961,119",USA,1664
45,SD,South Dakota,"865,454",USA,291
46,TN,Tennessee,"6,651,194",USA,1703
47,TX,Texas,"27,862,596",USA,4766
48,UT,Utah,"3,051,217",USA,1049
49,VA,Virginia,"8,411,808",USA,1983
50,VI,U.S. Virgin Islands,"103,574",USA,0
51,VT,Vermont,"624,594",USA,445
52,WA,Washington,"7,288,000",USA,5586
53,WI,Wisconsin,"5,778,708",USA,1862
54,WV,West Virginia,"1,831,102",USA,688
55,WY,Wyoming,"585,501",USA,293
56,ON,"ONTARIO,CAN","13,448,494",CAN,0
57,AB,"ALBERTA,CANADA","4,067,175",CAN,0
58,BC,"BRITISH COLUMBIA,CAN","4,648,055",CAN,0
59,Manitoba,"MANITOBA,CANADA","1,278,365",CAN,0
60,"NEW BRUNSWICK,CAN","NEW BRUNSWICK,CAN","747,101",CAN,0

In [40]:
df.index.get_loc(df.iloc[5].name)

5

In [41]:
#index = df.loc[df['State']=='DC'].index[0]
#index = df.loc[df['StateCode']=='CA'].index[0]
#index = df.loc[df['Country']=='USA'].index[0]
#df.loc[index, 'nsightings'] = 12
#df

In [42]:
sight_rate = [(df['StateCode'][n], df['nsightings'][n], 
  int(df['population'][n].replace (",", "") ),
  1000*float(df['nsightings'][n]) / int(df['population'][n].replace (",", ""))  )

  for n in range(len(df))]

In [43]:
# Sorted by the sighting rate
sorted_sight_rate = sorted(sight_rate, reverse=True, key=lambda x: x[3])
sorted_sight_rate

[('WA', 5586, 7288000, 0.7664654226125137),
 ('MT', 748, 1042520, 0.7174922303648851),
 ('VT', 445, 624594, 0.712462815845173),
 ('AK', 522, 741894, 0.7036045580635508),
 ('ME', 886, 1331479, 0.6654254404312798),
 ('NH', 829, 1334795, 0.6210691529410883),
 ('NM', 1204, 2081015, 0.5785638258253785),
 ('AZ', 3803, 6931071, 0.5486886514364085),
 ('ID', 879, 1683140, 0.5222381976543841),
 ('WY', 293, 585501, 0.500426130783722),
 ('NV', 1282, 2940058, 0.4360458195042411),
 ('RI', 448, 1056426, 0.4240713500046383),
 ('CO', 2272, 5540545, 0.4100679626282252),
 ('CT', 1350, 3576452, 0.3774690671089672),
 ('WV', 688, 1831102, 0.37573002487026935),
 ('MO', 2154, 6093000, 0.3535204332840965),
 ('HI', 500, 1428557, 0.35000353503570386),
 ('UT', 1049, 3051217, 0.34379724549253626),
 ('SD', 291, 865454, 0.3362397077141015),
 ('SC', 1664, 4961119, 0.335408201254596),
 ('CA', 12793, 39250017, 0.3259361645626803),
 ('WI', 1862, 5778708, 0.32221735377527294),
 ('DE', 298, 952065, 0.3130038390235961),
 ('KS', 897, 2907289, 0.308534858419648),
 ('IA', 942, 3134693, 0.3005078966265596),
 ('FL', 6061, 20612439, 0.2940457458721891),
 ('AR', 871, 2988248, 0.29147513860964686),
 ('MA', 1950, 6811779, 0.28626882933224934),
 ('OH', 3333, 11646273, 0.28618597554771386),
 ('MI', 2837, 9928301, 0.28574879025122224),
 ('PA', 3650, 12784227, 0.28550807178251764),
 ('MN', 1560, 5519952, 0.2826111531404621),
 ('IN', 1860, 6633053, 0.2804138607063746),
 ('KY', 1242, 4436974, 0.27992050437978677),
 ('NE', 529, 1907116, 0.27738218335958587),
 ('OK', 1075, 3923561, 0.2739858001443077),
 ('NC', 2731, 10146788, 0.2691492125389828),
 ('IL', 3428, 12801539, 0.26778030360255906),
 ('TN', 1703, 6651194, 0.2560442531070361),
 ('ND', 192, 757952, 0.2533141940386726),
 ('NJ', 2113, 8944469, 0.23623537629791103),
 ('VA', 1983, 8411808, 0.23574004542186414),
 ('MD', 1369, 6016447, 0.2275429335619511),
 ('NY', 4442, 19745289, 0.2249650536895155),
 ('AL', 1010, 4863300, 0.2076779141735036),
 ('MS', 592, 2988726, 0.19807770936512747),
 ('GA', 1978, 10310371, 0.19184566685330723),
 ('LA', 882, 4681666, 0.18839447324948),
 ('TX', 4766, 27862596, 0.171053695068471),
 ('PR', 37, 3411307, 0.010846282671128691),
 ('AS', 0, 54343, 0.0),
 ('DC', 0, 681170, 0.0),
 ('GU', 0, 161785, 0.0),
 ('MP', 0, 52344, 0.0),
 ('OR', 0, 4093465, 0.0),
 ('VI', 0, 103574, 0.0),
 ('ON', 0, 13448494, 0.0),
 ('AB', 0, 4067175, 0.0),
 ('BC', 0, 4648055, 0.0),
 ('Manitoba', 0, 1278365, 0.0),
 ('NEW BRUNSWICK,CAN', 0, 747101, 0.0)]

In [44]:
# sorted by the # of sightings
sorted_nsighting = sorted(sight_rate, reverse=True, key=lambda x: x[1])
sorted_nsighting

[('CA', 12793, 39250017, 0.3259361645626803),
 ('FL', 6061, 20612439, 0.2940457458721891),
 ('WA', 5586, 7288000, 0.7664654226125137),
 ('TX', 4766, 27862596, 0.171053695068471),
 ('NY', 4442, 19745289, 0.2249650536895155),
 ('AZ', 3803, 6931071, 0.5486886514364085),
 ('PA', 3650, 12784227, 0.28550807178251764),
 ('IL', 3428, 12801539, 0.26778030360255906),
 ('OH', 3333, 11646273, 0.28618597554771386),
 ('MI', 2837, 9928301, 0.28574879025122224),
 ('NC', 2731, 10146788, 0.2691492125389828),
 ('CO', 2272, 5540545, 0.4100679626282252),
 ('MO', 2154, 6093000, 0.3535204332840965),
 ('NJ', 2113, 8944469, 0.23623537629791103),
 ('VA', 1983, 8411808, 0.23574004542186414),
 ('GA', 1978, 10310371, 0.19184566685330723),
 ('MA', 1950, 6811779, 0.28626882933224934),
 ('WI', 1862, 5778708, 0.32221735377527294),
 ('IN', 1860, 6633053, 0.2804138607063746),
 ('TN', 1703, 6651194, 0.2560442531070361),
 ('SC', 1664, 4961119, 0.335408201254596),
 ('MN', 1560, 5519952, 0.2826111531404621),
 ('MD', 1369, 6016447, 0.2275429335619511),
 ('CT', 1350, 3576452, 0.3774690671089672),
 ('NV', 1282, 2940058, 0.4360458195042411),
 ('KY', 1242, 4436974, 0.27992050437978677),
 ('NM', 1204, 2081015, 0.5785638258253785),
 ('OK', 1075, 3923561, 0.2739858001443077),
 ('UT', 1049, 3051217, 0.34379724549253626),
 ('AL', 1010, 4863300, 0.2076779141735036),
 ('IA', 942, 3134693, 0.3005078966265596),
 ('KS', 897, 2907289, 0.308534858419648),
 ('ME', 886, 1331479, 0.6654254404312798),
 ('LA', 882, 4681666, 0.18839447324948),
 ('ID', 879, 1683140, 0.5222381976543841),
 ('AR', 871, 2988248, 0.29147513860964686),
 ('NH', 829, 1334795, 0.6210691529410883),
 ('MT', 748, 1042520, 0.7174922303648851),
 ('WV', 688, 1831102, 0.37573002487026935),
 ('MS', 592, 2988726, 0.19807770936512747),
 ('NE', 529, 1907116, 0.27738218335958587),
 ('AK', 522, 741894, 0.7036045580635508),
 ('HI', 500, 1428557, 0.35000353503570386),
 ('RI', 448, 1056426, 0.4240713500046383),
 ('VT', 445, 624594, 0.712462815845173),
 ('DE', 298, 952065, 0.3130038390235961),
 ('WY', 293, 585501, 0.500426130783722),
 ('SD', 291, 865454, 0.3362397077141015),
 ('ND', 192, 757952, 0.2533141940386726),
 ('PR', 37, 3411307, 0.010846282671128691),
 ('AS', 0, 54343, 0.0),
 ('DC', 0, 681170, 0.0),
 ('GU', 0, 161785, 0.0),
 ('MP', 0, 52344, 0.0),
 ('OR', 0, 4093465, 0.0),
 ('VI', 0, 103574, 0.0),
 ('ON', 0, 13448494, 0.0),
 ('AB', 0, 4067175, 0.0),
 ('BC', 0, 4648055, 0.0),
 ('Manitoba', 0, 1278365, 0.0),
 ('NEW BRUNSWICK,CAN', 0, 747101, 0.0)]